spring:
  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  security:
    jwt:
      header: Authorization
      # secret : kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360
      secret: a2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjA=
      access-token-validity-in-seconds: 86_400     # 1일
      refresh-token-validity-in-seconds: 1_209_600  # 2주

kakao:
  authorizeUrl: https://kauth.kakao.com/oauth/authorize
  authUrl: https://kauth.kakao.com/oauth/token
  userApiUrl: https://kapi.kakao.com/v2/user/me
  placeApiUrl: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
  restapiKey: ${REST_API_KEY}
  redirectUrl: api/v1/auth/callback


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
  org.springframework.security: debug

