spring:
  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  security:
    jwt:
      header: Authorization
      # secret : kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360-kernel360
      secret: a2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjAta2VybmVsMzYwLWtlcm5lbDM2MC1rZXJuZWwzNjA=
      access-token-validity-in-seconds: 86_400     # 1일
      refresh-token-validity-in-seconds: 1_209_600  # 2주

    oauth2:
      client:
        registration:
          kakao:
            client-id: ${REST_API_KEY}
            client-secret: ${CLIENT_SECRET}
            scope:
              - account_email
              - gender
              - birthyear
              - birthday
              - profile_nickname
            client-authentication-method: POST
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kakao:
  place-api-uri: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
  restapiKey: ${REST_API_KEY}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
  org.springframework.security: debug

